# Generated by Django 4.1 on 2023-10-12 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('dni', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{8,10}$', message='El número de dni debe tener entre 8 y 10 dígitos.')])),
                ('mail', models.EmailField(max_length=100, unique=True)),
                ('curriculu', models.FileField(upload_to='cv_upload/')),
                ('mensaje', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
