# Generated by Django 4.1 on 2023-11-04 16:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=150, verbose_name='Calle')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('cp', models.IntegerField(verbose_name='Código Postal')),
                ('piso', models.IntegerField(verbose_name='Piso')),
                ('departamento', models.CharField(max_length=150, verbose_name='Calle')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('mail', models.EmailField(max_length=150, null=True)),
                ('baja', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.persona')),
                ('dni', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{8,10}$', message='El número de dni debe tener entre 8 y 10 dígitos.')], verbose_name='DNI')),
                ('curriculum', models.FileField(upload_to='cv_upload/')),
                ('mensaje', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Postulantes',
            },
            bases=('core.persona',),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'Recibido'), ('2', 'Procesado'), ('3', 'Asignado'), ('4', 'Entregado'), ('5', 'No entregado en 1er visita'), ('6', 'No entregado en 2da visita')], default='1', max_length=3)),
                ('domicilio_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(verbose_name='Peso')),
                ('ancho', models.FloatField(verbose_name='Ancho')),
                ('largo', models.FloatField(verbose_name='Largo')),
                ('alto', models.FloatField(verbose_name='Alto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.persona')),
                ('cuit', models.IntegerField(verbose_name='CUIT')),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.domicilio')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
            bases=('core.persona',),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('postulante_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.postulante')),
                ('pedidos', models.ManyToManyField(to='core.pedido')),
            ],
            options={
                'verbose_name_plural': 'Empleados',
            },
            bases=('core.postulante',),
        ),
    ]
