# Generated by Django 4.1 on 2023-11-20 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='idlocalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.localidad'),
        ),
    ]
