# Generated by Django 4.1 on 2023-10-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='curriculu',
            new_name='curriculum',
        ),
    ]
