# Generated by Django 4.1 on 2023-10-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_curriculu_user_curriculum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Contacto',
        ),
    ]
