# Generated by Django 4.1 on 2023-10-13 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_user_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='lastname',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='name',
            new_name='nombre',
        ),
    ]
