# Generated by Django 4.1 on 2023-10-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_lastname_contacto_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
